NELUA=nelua
all:
	$(NELUA) day01.nelua
	$(NELUA) day02.nelua
	$(NELUA) day03.nelua
	$(NELUA) day04.nelua
	$(NELUA) day05.nelua
	$(NELUA) day06.nelua
	$(NELUA) day07.nelua
	$(NELUA) day08.nelua
	$(NELUA) day09.nelua
	$(NELUA) day10.nelua
	$(NELUA) day11.nelua
	$(NELUA) day12.nelua
	$(NELUA) day13.nelua
	$(NELUA) day14.nelua
	$(NELUA) day15.nelua
	$(NELUA) day16.nelua
	$(NELUA) day17.nelua
	$(NELUA) day18.nelua
	$(NELUA) day19.nelua
	$(NELUA) day20.nelua
	$(NELUA) day21.nelua
	$(NELUA) day22.nelua
	$(NELUA) day23.nelua
