NELUA=nelua
NELUAFLAGS=-DTEST
all:
	$(NELUA) $(NELUAFLAGS) day01.nelua
	$(NELUA) $(NELUAFLAGS) day02.nelua
	$(NELUA) $(NELUAFLAGS) day03.nelua
	$(NELUA) $(NELUAFLAGS) day04.nelua
	$(NELUA) $(NELUAFLAGS) day05.nelua
	$(NELUA) $(NELUAFLAGS) day06.nelua
	$(NELUA) $(NELUAFLAGS) day07.nelua
	$(NELUA) $(NELUAFLAGS) day08.nelua
	$(NELUA) $(NELUAFLAGS) day09.nelua
	$(NELUA) $(NELUAFLAGS) day10.nelua
	$(NELUA) $(NELUAFLAGS) day11.nelua
	$(NELUA) $(NELUAFLAGS) day12.nelua
	$(NELUA) $(NELUAFLAGS) day13.nelua
	$(NELUA) $(NELUAFLAGS) day14.nelua
	$(NELUA) $(NELUAFLAGS) day15.nelua
	$(NELUA) $(NELUAFLAGS) day16.nelua
	$(NELUA) $(NELUAFLAGS) day17.nelua
	$(NELUA) $(NELUAFLAGS) day18.nelua
	$(NELUA) $(NELUAFLAGS) day19.nelua
	$(NELUA) $(NELUAFLAGS) day20.nelua
	$(NELUA) $(NELUAFLAGS) day21.nelua
	$(NELUA) $(NELUAFLAGS) day22.nelua
	$(NELUA) $(NELUAFLAGS) day23.nelua
	$(NELUA) $(NELUAFLAGS) day24.nelua
	$(NELUA) $(NELUAFLAGS) day25.nelua
